name: Obsidian Backup

on:
  schedule:
    - cron: "0 2 * * *"  # daily 2 AM
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip vault
        run: |
          zip -r obsidian-backup.zip . \
          -x ".git/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: obsidian-backup
          path: obsidian-backup.zip
